//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Contracts = new HashSet<Contract>();
            this.Operations = new HashSet<Operation>();
            this.WeaponHistories = new HashSet<WeaponHistory>();
        }
    
        public int IDAgent { get; set; }
        public int IDHuman { get; set; }
        public int IDAgentSpecialization { get; set; }
        public int IDMTF { get; set; }
        public int IDAgentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual Human Human { get; set; }
        public virtual MTF MTF { get; set; }
        public virtual AgentStatu AgentStatu { get; set; }
        public virtual AgentSpecialization AgentSpecialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponHistory> WeaponHistories { get; set; }
    }
}
