//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int IDContract { get; set; }
        public int IDAgent { get; set; }
        public Nullable<System.DateTime> StartContactDate { get; set; }
        public Nullable<System.DateTime> EndContractDate { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
