//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.WeaponHistory = new HashSet<WeaponHistory>();
        }
    
        public int IDOperation { get; set; }
        public int IDOrder { get; set; }
        public string OperationName { get; set; }
        public int IDOperationType { get; set; }
        public int IDCommander { get; set; }
        public int IDMTF { get; set; }
        public Nullable<System.DateTime> OperationStartDate { get; set; }
        public Nullable<System.DateTime> OperationEndDate { get; set; }
        public int IDOperationStatus { get; set; }
        public string Raport { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual MTF MTF { get; set; }
        public virtual OperationStatus OperationStatus { get; set; }
        public virtual OperationType OperationType { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponHistory> WeaponHistory { get; set; }
    }
}
