//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IDUser { get; set; }
        public int IDHuman { get; set; }
        public int IDRole { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string RegCode { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual Role Role { get; set; }
    }
}
