//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponHistory
    {
        public int IDWeaponHistory { get; set; }
        public int IDOperation { get; set; }
        public int IDAgent { get; set; }
        public int IDWeapon { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
