//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weapon()
        {
            this.WeaponForAgentSpecs = new HashSet<WeaponForAgentSpec>();
            this.WeaponHistories = new HashSet<WeaponHistory>();
            this.WeaponStoreLogs = new HashSet<WeaponStoreLog>();
        }
    
        public int IDWeapon { get; set; }
        public string WeaponName { get; set; }
        public int IDWeaponType { get; set; }
        public int IDCaliber { get; set; }
        public decimal Weight { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Caliber Caliber { get; set; }
        public virtual WeaponType WeaponType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponForAgentSpec> WeaponForAgentSpecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponHistory> WeaponHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponStoreLog> WeaponStoreLogs { get; set; }
    }
}
