//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponForAgentSpec
    {
        public int IDWeaponForAgentSpec { get; set; }
        public int IDWeapon { get; set; }
        public int IDAgentSpecialization { get; set; }
    
        public virtual AgentSpecialization AgentSpecialization { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
