//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponStoreLog
    {
        public int IDStoreLog { get; set; }
        public int IDWeapon { get; set; }
        public int IDWeaponProducer { get; set; }
        public string SerialNum { get; set; }
        public int IDWeaponStatus { get; set; }
    
        public virtual Weapon Weapon { get; set; }
        public virtual WeaponProducer WeaponProducer { get; set; }
        public virtual WeaponStatu WeaponStatu { get; set; }
    }
}
