//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponStoreLog
    {
        public int IDStoreLog { get; set; }
        public int IDWeapon { get; set; }
        public int IDWeaponProducer { get; set; }
        public string SerialNum { get; set; }
        public int IDWeaponStatus { get; set; }
    
        public virtual Weapon Weapon { get; set; }
        public virtual WeaponProducer WeaponProducer { get; set; }
        public virtual WeaponStatus WeaponStatus { get; set; }
    }
}
