//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIMORepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponHistory
    {
        public int IDWeaponHistory { get; set; }
        public int IDOperation { get; set; }
        public int IDAgent { get; set; }
        public int IDWeapon { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
